version: '3.8'

services:
  app:
    build: .
    ports:
      - "4060:4060"
    environment:
      - NODE_ENV=production
      - PORT=4060
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      # Add other environment variables as needed
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: